### ISSUE TITLE
How the heck does one use this thing?!

### ISSUE THREAD

**Issue by kenny1983** [Kinnay/Wii-U-Debugger#3]
Hey I was just wondering how to use this program...I have loaded it on my Wii U with wiiload, chose the "install and return to system menu" option, and now it's waiting for a debugger connection. How do I establish one??

I'm trying to debug a piece of homebrew that I'm working on, but it looks as though you only support debugging proper game discs...is that correct? Or what am I missing? MTIA :-)

**Comment by kinnay** [comment]
Run main.py on your computer. Enter the IP address of your Wii U at the bottom and click the 'connect' button (see screenshots).

Only real titles can be debugged, but it supports both discs and digital titles.

**Comment by kenny1983** [comment]
Ah thank you very much for the quick and informative answer! One more question before I leave you in peace: do you know of any good GUI tools similar to yours that allow homebrew to be debugged? If not, how would I use udpdebugreader to achieve the same? Thanks again! :D

**Comment by kinnay** [comment]
Sorry, I don't really know anything about other homebrew tools. I've never even heard of udpdebugreader.

**Comment by kenny1983** [comment]
No worries, thanks anyway for replying! 😀
